v2

diff --git a/build_spec.yaml b/build_spec.yaml
--- a/build_spec.yaml
+++ b/build_spec.yaml
@@ -19,20 +19,20 @@ steps:
       export BUILDRUN_HASH=$(echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7)
       echo "BUILDRUN_HASH: $BUILDRUN_HASH"
 
-  # Step 2: Debug - List Files in frontend Directory
-  - type: Command
-    name: "Verify Frontend Directory Contents"
-    timeoutInSeconds: 60
-    command: |
-      echo "Listing files in frontend directory:"
-      ls ./frontend
-
-  # Step 3: Build Frontend Docker Image
+  # Step 2: Build Frontend Docker Image
   - type: Command
     name: "Build Frontend Container Image"
     timeoutInSeconds: 3600
     command: |
       docker build --pull --rm -t mlbroker-frontend:$BUILDRUN_HASH -f frontend/Dockerfile ./frontend || { echo "Frontend build failed"; exit 1; }
+
+  # Step 3: Build Backend Docker Image
+  - type: Command
+    name: "Build Backend Container Image"
+    timeoutInSeconds: 3600
+    command: |
+      docker build --pull --rm -t mlbroker-backend:$BUILDRUN_HASH -f backend/Dockerfile ./backend || { echo "Backend build failed"; exit 1; }
+
 
   # Step 4: Build Backend Docker Image
   - type: Command
